
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true


app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
